# Generated by Django 2.0.1 on 2018-01-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_descriptive',
            name='qid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examapp.Question'),
        ),
        migrations.AlterField(
            model_name='question_fillup',
            name='qid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examapp.Question'),
        ),
        migrations.AlterField(
            model_name='question_mcq_multiple',
            name='qid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examapp.Question'),
        ),
        migrations.AlterField(
            model_name='question_mcq_single',
            name='qid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='examapp.Question'),
        ),
    ]
