# Generated by Django 2.0.1 on 2018-01-22 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20180120_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('tid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=250)),
                ('conducted_by', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='question_descriptive',
            old_name='qid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question_fillup',
            old_name='qid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question_mcq_multiple',
            old_name='qid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question_mcq_single',
            old_name='qid',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examapp.Test'),
        ),
    ]
