# Generated by Django 2.0.4 on 2018-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluated',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
